### ISSUE TITLE
Searching never completes

### ISSUE THREAD

**Issue by MattKneale** [bachya/lp-vault-manager#4] opened 2015-01-06 15:19 UTC
Having problems after setting everything up. I've managed to get logged in successfully after setting my email, but now whenever searching the vault it just says "Searching...." and stays like that. AFAIK I've followed instructions to the letter!

Any ideas?

**Comment by bachya** [comment] 2015-01-06 15:55
Hi Matt – sorry to hear that you're having trouble. This likely is a duplicate of #3, which I'm still researching. I'm going to close this; keep an eye on that one and if it turns out that you've reported a separate issue, we'll re-open this. Sound good?

**Closed by bachya** 2015-01-06 15:55 UTC

**Comment by MattKneale** [comment] 2015-01-06 15:57
That's fine, sorry I didn't check properly first! I'll head over to #3.
